"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeContext from "../_contexts/Theme";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spawn Next App",
  description: "Generated by spawn-next-app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [theme, setTheme] = useState("light");
  return (
    <ThemeContext.Provider value={{ theme, setTheme }}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ThemeContext.Provider>
  );
}
